<a href="https://colab.research.google.com/github/eildes06/Inclassnotesandcodes/blob/main/DAwPy_S2_(Numpy_Indexing_Selection_Operations)_benim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2</p><h1>

In [1]:
import numpy as np

In [3]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [4]:
#indexin selection yapacaksam once koseli parantez acicam
arr[8]

8

In [5]:
arr[-3]

8

In [6]:
arr[2:5]

array([2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
#0 ile10 arasi tek sayilar
arr[1::2]

array([1, 3, 5, 7, 9])

In [ ]:
#ciftler 
arr[::2]

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [10]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [11]:
#1.satir getirvirgul koymazsam satirla islem yapiyoruz ilk tarafi kale aliyor
arr_2d[1]

array([20, 25, 30])

In [12]:
arr_2d[1][1]

25

In [13]:
arr_2d[1,1]#satir sutun kesistir yukardaki de dogru ama bu kullanilri

25

In [14]:

arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
#arayin icinden 40 in yerine 99 yapalim

In [15]:
arr_2d[2,1]=99

In [16]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 99, 45]])

In [19]:
arr_2d[1:,:2]


array([[20, 25],
       [35, 99]])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [17]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [18]:
v=np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [21]:
v[[3,5,7]]

array([ 9, 15, 21])

In [ ]:
#icerdeki koseli parantezi yapmazsan hata verir onemli

In [22]:
v[[3,5]]

array([ 9, 15])

In [23]:
arr2d=np.zeros((10,10),dtype=int)
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [26]:
for i range(len(arr2d)):
    arr2d[i]=i
arr2d

SyntaxError: ignored

In [28]:
arr2d[[2,4,6]]#bu eksik. bole cikmiyor

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

<h3>any_array[[row indices], [column indices]]</h3>

In [32]:
jj=np.arange(1,17).reshape(4,4)

In [33]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [34]:
jj[[1,2],[0,3]]

array([ 5, 12])

### Using ***basic index*** and ***fancy index*** together

In [35]:
jj[2,[2,3]]

array([11, 12])

In [36]:
jj[[2,3],2]

array([11, 15])

### Using ***basic slicing*** and ***fancy index*** together

In [37]:
jj#vilgulun solu row sago colum tek koseli parantez icin

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [38]:
jj[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

# Selection on a Condition

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [39]:
arr=np.arange(1,11)

In [40]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [42]:
arr[arr>4]
#true olanlarin degerlerini dondurur

array([ 5,  6,  7,  8,  9, 10])

In [43]:
arr[(arr>3)&(arr<8)]#iki ayri conditionu parantez icinde yazmali

array([4, 5, 6, 7])

In [44]:
arr[arr!=4]

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10])

# Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

https://numpy.org/doc/stable/user/theory.broadcasting.html

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr[:5]

array([1, 2, 3, 4, 5])

In [47]:
arr[:5]=99

In [48]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [49]:
arr_slice=arr[5:]
arr_slice

array([ 6,  7,  8,  9, 10])

In [50]:
arr_slice[-2:]=55

In [51]:
arr_slice

array([ 6,  7,  8, 55, 55])

In [52]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8, 55, 55])

In [ ]:
#gordugum gibi burda yapilan degisiklik digerlerini ekliyr.etkilemsin diye copy kullanmaliyiz:)

In [56]:
arr_copy=arr.copy()

In [57]:
arr_copy

array([99, 99, 99, 99, 99,  6,  7,  8, 55, 55])

In [58]:
arr_copy[2:6]

array([99, 99, 99,  6])

In [59]:
arr

array([99, 99, 99, 99, 99,  6,  7,  8, 55, 55])

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [60]:
arr=np.arange(0,10)

In [61]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [64]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [67]:
#hatayi ignore ediyor en basta bunu calistirabilirsin
import warnings
warnings.filterwarnings('ignore')

In [66]:
arr/arr

array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
#0/0 none dedi normalde hata verir warning yaptik ya hata vermedi

In [68]:
1/arr

array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [69]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [70]:
arr+1#her elemana 1 ekliyor

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [70]:
#yukarkdaki aritmatik islemleri fonklar ilede yapabilirizz

In [71]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [74]:
np.sin(np.pi/4)

0.7071067811865475

In [75]:
np.tan(np.pi/4)

0.9999999999999999

In [76]:
np.pi

3.141592653589793

In [78]:
np.log(1000)

6.907755278982137

In [79]:
np.log10(100)

2.0

In [ ]:
#log yazinca e tabanina gore aliyor

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``np.corrcoef(arr)`` | Returns correlation coefficient of array

In [80]:
v=np.array([1,1,2,2,3,3,3])
v

array([1, 1, 2, 2, 3, 3, 3])

In [81]:
np.mean(v)

2.142857142857143

In [82]:
v.mean()

2.142857142857143

In [85]:
np.median(v)

2.0

In [87]:
np.std(v)

0.8329931278350429

In [88]:
v.var()

0.6938775510204082

In [89]:
v=np.array([1,1,2,2,3,3,3])
v
np.random.seed(42)
xarr = np.random.randn(3,3)
xarr

array([[ 0.49671415, -0.1382643 ,  0.64768854],
       [ 1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439]])

In [90]:
np.corrcoef(xarr)

array([[ 1.        ,  0.33500663, -0.29669929],
       [ 0.33500663,  1.        ,  0.80039247],
       [-0.29669929,  0.80039247,  1.        ]])

In [ ]:
#ayni sutunu ayni stunla karsilastirirsan korelasyon birdir koseler

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.