<a href="https://colab.research.google.com/github/eildes06/Inclassnotesandcodes/blob/main/DAwPy_S3_(Pandas_Series)_benim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 3</p><h1>

# Pandas Series

In [1]:
import numpy as np
import pandas as pd


## Creating a Pandas Series

pd.Series(data=None, index=None, dtype=None, name=None, copy=False, fastpath=False)

One-dimensional ndarray with axis labels (including time series).

In [2]:
labels = ['a','b','c']
my_list = [10, 20, 30]
arr = np.array([10, 20, 30])
d = {'a': 10, 'b': 20, 'c': 30}

### **Using Lists**

In [3]:
pd.Series(labels)#indexleri otomatik verdi


0    a
1    b
2    c
dtype: object

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [5]:
pd.Series([10,20,30])

0    10
1    20
2    30
dtype: int64

### **Using NumPy Arrays**

In [6]:
arr

array([10, 20, 30])

In [7]:
pd.Series(data=arr)

0    10
1    20
2    30
dtype: int64

In [10]:
pd.Series(data=arr,index=labels)

a    10
b    20
c    30
dtype: int64

### **Using Dictionary**

In [11]:
d

{'a': 10, 'b': 20, 'c': 30}

In [12]:
pd.Series(d)

a    10
b    20
c    30
dtype: int64

In [13]:
pd.Series(d,index=["q","c","y"])#sadece eslesenleri getirir
#int ile float karsilasrisa floata gecer aksi data kaybedersin

q     NaN
c    30.0
y     NaN
dtype: float64

### Using Scalar Value

In [14]:
pd.Series(data="Ahmet")

0    Ahmet
dtype: object

In [16]:
pd.Series(data="ahmet",index=range(1,5))

1    ahmet
2    ahmet
3    ahmet
4    ahmet
dtype: object

### Data in a Series

A pandas Series can hold a variety of object types:

{} or set()

In [17]:
set1=(1,3,2,6)

In [18]:
pd.Series(set1)

0    1
1    3
2    2
3    6
dtype: int64

In [20]:
set1= set([1,2,3,6])
set1

{1, 2, 3, 6}

In [21]:
pd.Series([set,list,dict])

0     <class 'set'>
1    <class 'list'>
2    <class 'dict'>
dtype: object

In [23]:
pd.Series([set,list,dict])[0]([2,5,7,8,2])# 0 ile indexliyor seti aldi o yuzden

{2, 5, 7, 8}

In [24]:
pd.Series([sum,print,len])[0]([3,5,7])#hangi index yaziliysa o islemi ypar

15

In [25]:
mix_data = ['Aziz', 2, True]

In [26]:
ser=pd.Series(mix_data)

In [27]:
ser#karisikm olursa object dondurur

0    Aziz
1       2
2    True
dtype: object

In [28]:
ser.dtype#icindeki elemanlarin data tipi


dtype('O')

In [29]:
type(ser)#data nin genel tipi ne

pandas.core.series.Series

In [30]:
type(ser[2])

bool

In [31]:
arr=np.array(mix_data)
arr

array(['Aziz', '2', 'True'], dtype='<U4')

In [32]:
type(arr[2])

numpy.str_

In [33]:
ser=pd.Series(np.random.randint(0,100,7))

In [34]:
ser

0    50
1    79
2    52
3    81
4    36
5    28
6    95
dtype: int64

In [36]:
ser.dtype

dtype('int64')

In [37]:
type(ser)

pandas.core.series.Series

In [38]:
ser.shape

(7,)

In [40]:
ser.size

7

In [41]:
len(ser)

7

In [42]:
ser.ndim#boyut sayisi

1

In [43]:
ser.index#bunu gormek icin listeye atmali

RangeIndex(start=0, stop=7, step=1)

In [44]:
list(ser.index)

[0, 1, 2, 3, 4, 5, 6]

In [46]:
for i in ser.index:
    print(i)

0
1
2
3
4
5
6


In [47]:
ser.keys()

RangeIndex(start=0, stop=7, step=1)

In [ ]:
#index yerine key yazarsan da ayni islemi yaapr

In [49]:
ser.values

array([50, 79, 52, 81, 36, 28, 95])

In [51]:
ser.item#bazi yerlerde parantezli bazi parantessiz bi r kurali yok kullanarak ogreneceksin

<bound method IndexOpsMixin.item of 0    50
1    79
2    52
3    81
4    36
5    28
6    95
dtype: int64>

In [52]:
ser.items()

In [53]:
list(ser.items())

[(0, 50), (1, 79), (2, 52), (3, 81), (4, 36), (5, 28), (6, 95)]

In [55]:
for index, value in ser.items():
    print(f"index:{index},value:{value}")

index:0,value:50
index:1,value:79
index:2,value:52
index:3,value:81
index:4,value:36
index:5,value:28
index:6,value:95


In [56]:
ser = pd.Series(data = np.random.randint(0,25,10), index = [i for i in "cbaefdgihj"])

In [57]:
ser

c    24
b     3
a    19
e    12
f     2
d    18
g    18
i     5
h    14
j     2
dtype: int64

In [58]:
for index, value in ser.items():
    print(f"index: {index}, value: {value}")

index: c, value: 24
index: b, value: 3
index: a, value: 19
index: e, value: 12
index: f, value: 2
index: d, value: 18
index: g, value: 18
index: i, value: 5
index: h, value: 14
index: j, value: 2


In [59]:
ser.head()#ilk bastaki 5 deger

c    24
b     3
a    19
e    12
f     2
dtype: int64

In [60]:
ser.tail()#sondan 5 satur

d    18
g    18
i     5
h    14
j     2
dtype: int64

In [ ]:
ser.sample(3)#random olarak kactane istersen o kdar randomly getirir

In [61]:
ser.sort_index(ascending=True)#indexsimi alfabetk siraladi

a    19
b     3
c    24
d    18
e    12
f     2
g    18
h    14
i     5
j     2
dtype: int64

In [ ]:
#indexsi siraladigi gibi degerleri de siralar
#alabetik seye gore siralar

In [16]:
ser.sort_values(ascending=False)#ture kucukten buyuge default u true dur
#false tam aksi siralar

In [62]:
ser

c    24
b     3
a    19
e    12
f     2
d    18
g    18
i     5
h    14
j     2
dtype: int64

In [63]:
ser.isin([5,9])#benim degerlerimden hangileri 5 ve 9 

c    False
b    False
a    False
e    False
f    False
d    False
g    False
i     True
h    False
j    False
dtype: bool

In [64]:
ser.isin([3,8])#hangileri bu listedeyse true aksi false

c    False
b     True
a    False
e    False
f    False
d    False
g    False
i    False
h    False
j    False
dtype: bool

In [ ]:
#mesela a ve b olarnlari z yap, 30 olanlari 40 yap gibi veri degistirmede kullancan

In [66]:
pd.Series([i for i in "clarusway"])

0    c
1    l
2    a
3    r
4    u
5    s
6    w
7    a
8    y
dtype: object

### Basic Attributes of Series

In [58]:
#bunun kiler biraz yukrada karismis

## Indexing Pandas Series

The key to using a Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look up of information.

Let's see some examples of how to grab information from a Series. Let us create two sereis, ser1 and ser2:

In [67]:
ser1 = pd.Series([1,2,3,4],index = ['USA', 'Germany','USSR', 'Japan'])
ser2 = pd.Series([1,2,5,4],index = ['USA', 'Germany','Italy', 'Japan'])

In [68]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [69]:
ser2#value llerim rakam index degerlerim sehirler

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [70]:
ser1.sort_index()#alfabetik siraya gore yerlestirdi

Germany    2
Japan      4
USA        1
USSR       3
dtype: int64

In [71]:
ser2.sort_values()

USA        1
Germany    2
Japan      4
Italy      5
dtype: int64

In [72]:
#1 . elamni cekelim indexler string ifade olmasina ragmen arkada 0 lari 1 leri tutuyor
ser1[1]

2

In [76]:
ser1["Germany"]

2

In [ ]:
#index cekerken. illa paranez index yapmana gerek yok cok tercih edilmez



3string ise calisiri ama rakamda calismaz

In [77]:
ser1.Germany

2

In [78]:
ser1+ser2#ayniindex varsa topluyor yksa non ceviryor

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

Operations are then also done based off of index:

In [79]:
ser3 = pd.Series(data = ["a", "b", "c", "d"])
ser3

0    a
1    b
2    c
3    d
dtype: object

In [80]:
ser3[0]

'a'

In [81]:
ser[:2]#nbastan 2 sec getir

c    24
b     3
dtype: int64

In [82]:
#tersden siralar
ser3[::-1]

3    d
2    c
1    b
0    a
dtype: object

### pandas_series[index] | pandas_series[[indices, indices...]]

In [83]:
panser = pd.Series(data = [121, 200, 150, 99], index = ["terry", "micheal", "orion", "jason"])
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [84]:
panser[["terry","orion"]]#istediklerimi getir dataframde stunlari cagirmak gibi

terry    121
orion    150
dtype: int64

In [85]:
panser["terry":"orion"]#veya arya 2 nokta koy extra parantezi sil

terry      121
micheal    200
orion      150
dtype: int64

In [87]:
panser[0:3]# ismiyle cagirirsan bas son dahoill olur isimler ile cagirisak isimlerin ikiside dahil
#ama normalde dahil etmiyordu 

terry      121
micheal    200
orion      150
dtype: int64

### Recap for Several Selecting Attributes

In [88]:
panser

terry      121
micheal    200
orion      150
jason       99
dtype: int64

In [89]:
panser.keys()

Index(['terry', 'micheal', 'orion', 'jason'], dtype='object')

In [90]:
panser.values

array([121, 200, 150,  99])

In [91]:
panser.values()

TypeError: ignored

In [92]:
panser.items()

In [ ]:
#item items farki item yaparsam bise donduruyor ama istedigim degil
#serimi farkli bozuk formatta yapiyor
#ama items bana iterable object donduruyor ama goremiyorum
#for donsusu icine koyarsam iterable data object dondurur
#for ile gezerim 

In [93]:
panser.item

<bound method IndexOpsMixin.item of terry      121
micheal    200
orion      150
jason       99
dtype: int64>

In [94]:
for index, value in panser.items():
    print(index, value)

terry 121
micheal 200
orion 150
jason 99


In [95]:
"terry"in panser#sadece panser yazdiginda value almaaz

True

In [96]:
121 in panser

False

In [97]:
200 in panser.values

True

In [98]:
panser.isin([200,150])

terry      False
micheal     True
orion       True
jason      False
dtype: bool

In [99]:
#terry 90 yapmak istiyorum
panser["terry"]=90

In [100]:
panser

terry       90
micheal    200
orion      150
jason       99
dtype: int64

In [101]:
panser[panser>100]

micheal    200
orion      150
dtype: int64

In [102]:
panser[panser>100]=175

In [103]:
panser

terry       90
micheal    175
orion      175
jason       99
dtype: int64