<a href="https://colab.research.google.com/github/eildes06/Inclassnotesandcodes/blob/main/DAwPy_S4_(Pandas_DataFrames%2C_Selection_and_Indexing)_ididit.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="CLRSWY"></p>

___

<h1><p style="text-align: center;">Pandas Lesson, Session - 4</p><h1>
    

# Data Frames

 - ### ``DataFrames`` are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [ ]:
import numpy as np
import pandas as pd


 ## Creating a DataFrame using the ``list``s of data and columns

pd.DataFrame(data=None, index=None, columns=None, dtype=None, copy=False)

Two-dimensional, size-mutable, potentially heterogeneous tabular data.

In [ ]:
data = [1, 3, 5, 7, 9, 18]
data

[1, 3, 5, 7, 9, 18]

In [ ]:
pd.DataFrame(data=data)#listeden bir data frame olusturdm

0
0   1
1   3
2   5
3   7
4   9
5  18

In [ ]:
#seri olustursaydim formattan anliyoruz. ayrica seride ve dataframe calsian seriler
#methodlar farklidir

In [ ]:
pd.Series(data=data)

0     1
1     3
2     5
3     7
4     9
5    18
dtype: int64

In [ ]:
pd.DataFrame(data=data,columns=["col_1"])

col_1
0      1
1      3
2      5
3      7
4      9
5     18

In [ ]:
pd.DataFrame(data=data, columns=["col_1"])

col_1
0      1
1      3
2      5
3      7
4      9
5     18

In [ ]:
m = np.arange(1,24,2).reshape(3,4)
m

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

 ## Creating a DataFrame using a ``NumPy Arrays``

In [ ]:
df=pd.DataFrame(data=m, columns=['var1','var2','var3','var4'])
df#df _agaclar bise yaz acikla yani eger birden fazla df kullanacaksan lazim

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
#colum ismi yazacaksan kac sutun varsa o kadar isim yazman lazim

In [ ]:
df.head()

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
df.head(1)

var1  var2  var3  var4
0     1     3     5     7

In [ ]:
df.head(-1)

var1  var2  var3  var4
0     1     3     5     7
1     9    11    13    15

In [ ]:
df.sample()

NameError: ignored

In [ ]:
df.columns #sutunlari cagirirsin

Index(['var1', 'var2', 'var3', 'var4'], dtype='object')

In [ ]:
#mesela sutundaki sayilari almak istiyorsun onlari cagirip islemyaparsin for dongusuylen

In [ ]:
for i in df.columns:
    print(df[i].sum())#tekk tek sutunlar uzerinde dolasiyor islem yapiyor

27
33
39
45


In [ ]:
#sutunlarin colum  ismini degistirmek istiym kolum sayisi kadar yaz
df.columns=["new1","new2","new3","new4"]

In [ ]:
df#kac sutun varsa o kadar yazman lazim

new1  new2  new3  new4
0     1     3     5     7
1     9    11    13    15
2    17    19    21    23

In [ ]:
df.columns=["new1","new2","new4"]#az yazdiginda fazla hata verir

ValueError: ignored

In [ ]:
df

new1  new2      new4
0     1     3   5     7
1     9    11  13    15
2    17    19  21    23

In [ ]:
df.index=["a","b","c"]

In [ ]:
df

new1  new2      new4
a     1     3   5     7
b     9    11  13    15
c    17    19  21    23

In [ ]:
#sadece bir sutun ya satir ismi degistirmek istiyorsanda

In [ ]:
df.rename(columns={"new1":"a","new2":"b"})
                   #nereyi degistirmek neyle degistirmek istiyon yaz

a   b      new4
a   1   3   5     7
b   9  11  13    15
c  17  19  21    23

In [ ]:
df.rename(index={"a":1,"b":2})

new1  new2      new4
1     1     3   5     7
2     9    11  13    15
c    17    19  21    23

In [ ]:
#kalici degiislik icin inplacce kullanilir

In [ ]:
#bunlari kalici yapmadi,
df.shape

(3, 4)

In [ ]:
df.shape[1]

4

In [ ]:
df

new1  new2      new4
a     1     3   5     7
b     9    11  13    15
c    17    19  21    23

In [ ]:
df.ndim

2

In [ ]:
df.size

12

In [ ]:
len(df)#satur sayisi

3

In [ ]:
df.values

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15],
       [17, 19, 21, 23]])

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(df.values)

numpy.ndarray

 ## Creating a DataFrame using a ``dict``

In [ ]:
s1 = np.random.randint(2,10, size = 4)
s2 = np.random.randint(3,10, size = 4)
s3 = np.random.randint(4,15, size = 4)

In [ ]:
s1

array([7, 3, 3, 9])

In [ ]:
s2

array([8, 9, 5, 5])

In [ ]:
s3

array([ 6, 12,  8,  6])

In [ ]:
my_dict = {"var1":s1, "var2":s2, "var3":s3}#her bir sutuna bir aray atadik
my_dict

{'var1': array([7, 3, 3, 9]),
 'var2': array([8, 9, 5, 5]),
 'var3': array([ 6, 12,  8,  6])}

In [ ]:
df1=pd.DataFrame(my_dict)

In [ ]:
df1

var1  var2  var3
0     7     8     6
1     3     9    12
2     3     5     8
3     9     5     6

In [ ]:
df1.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
[i for i in df1.index]

[0, 1, 2, 3]

In [ ]:
"var2" in df1

True

### Now, let's examine again the ***idexing, selection*** and ***slicing*** methods and several ***attributes*** using a different DataFrame

In [ ]:
from numpy.random import randn

In [ ]:
np.random.seed(101)#5 e dortluk array olusturdu
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3#split bosluklaraa gore bir liste haline getirdi 

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

In [ ]:
"A B C D E".split

<function str.split>

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [ ]:
df3["W"]#w kolumunu sutunu  bir seri gibi getirdi bu bir seri

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
type(df3["W"])# tipi seri

pandas.core.series.Series

In [ ]:
#cift koseli parantez 

In [ ]:
df3[["W"]]#koseli parantez ile cagirince data frame gelr

W
A  2.706850
B  0.651118
C -2.018168
D  0.188695
E  0.190794

In [ ]:
type(df3[["w"]])#cagirirken .cagirdigi bazen hata veriyor degisiklik yapmiyor

In [ ]:
df3.W#bazen nokta ile cagırdıgında method,function vs seklınde algılayıp hata verebiliyor

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [ ]:
df3.W #sutun icinde kalici degisiklik yapmaz

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[["W","Y"]]#koeli parasntez liste icinde cagirirsam bana ilgili seyleri getirir

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813
D  0.188695 -0.933237
E  0.190794  2.605967

In [ ]:
df3["W":"Y"]# index iincde w ve y yi aredi 
#

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [ ]:
df3["A":"C"]#string oldugu icin 2 side dahil veriyor

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001

In [ ]:
df3["A":"C"]["W"]#hangi sutunlari istiyorsam onu getirir
# 2seri ile ilgili islem yaparsak pandaya geciyor cift parantez yapiyourz

A    2.706850
B    0.651118
C   -2.018168
Name: W, dtype: float64

In [ ]:
df3["A":"C"][["W","Y"]]#birden fazla getirmekicin 2 parantez kullandikm yoksa hata verir.

W         Y
A  2.706850  0.907969
B  0.651118 -0.848077
C -2.018168  0.528813

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3['new']=df3['X']*df3['Y']
df3

W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  0.570325
B  0.651118 -0.319318 -0.848077  0.605965  0.270806
C -2.018168  0.740122  0.528813 -0.589001  0.391387
D  0.188695 -0.758872 -0.933237  0.955057  0.708208
E  0.190794  1.978757  2.605967  0.683509  5.156577

In [ ]:
df3["new2"]=[1,2,3,4,5]
df3

W         X         Y         Z       new  new2
A  2.706850  0.628133  0.907969  0.503826  0.570325     1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806     2
C -2.018168  0.740122  0.528813 -0.589001  0.391387     3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208     4
E  0.190794  1.978757  2.605967  0.683509  5.156577     5

In [ ]:
df3.columns=["new","new2","W","X","Y","Z"]#sirayi degistirme
df3

new      new2         W         X         Y  Z
A  2.706850  0.628133  0.907969  0.503826  0.570325  1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806  2
C -2.018168  0.740122  0.528813 -0.589001  0.391387  3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208  4
E  0.190794  1.978757  2.605967  0.683509  5.156577  5

In [ ]:
df3=df3[["new","new","new2"]]#insert ile yeni ekledihginiz seyi nereye ekleyeceginiz gosteriyorsnunz

In [ ]:
df3 = df3[["new", "new2", "W", "X", "Y", "Z"]]#sutunlar veya 2. boyut devreye girdigi zaman  hep cift oarantez
df3

new      new2         W         X         Y  Z
A  2.706850  0.628133  0.907969  0.503826  0.570325  1
B  0.651118 -0.319318 -0.848077  0.605965  0.270806  2
C -2.018168  0.740122  0.528813 -0.589001  0.391387  3
D  0.188695 -0.758872 -0.933237  0.955057  0.708208  4
E  0.190794  1.978757  2.605967  0.683509  5.156577  5

In [ ]:
#cikarma icin drop yapicaz
df3.drop("new2",axis=1)

new         W         X         Y  Z
A  2.706850  0.907969  0.503826  0.570325  1
B  0.651118 -0.848077  0.605965  0.270806  2
C -2.018168  0.528813 -0.589001  0.391387  3
D  0.188695 -0.933237  0.955057  0.708208  4
E  0.190794  2.605967  0.683509  5.156577  5

In [ ]:
#birden fazla dusurmek icin basina liste eklemen lazim
df3.drop(["new","new2"], axis=1)#axis demek gel sutunlarda bak derim

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
df3.drop(columns=["new","new2"])#axis belirtmemek icin colum yazariz

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
#kalici degiisklik icin
df3.drop(["new", "new2"], axis=1, inplace=True)

In [ ]:
df3

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

#### DataFrame Columns are just Series

**Creating a new column:**

## [Removing Columns & Rows](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-drop.ipynb)

 ### Removing Columns

In [ ]:
df3.drop("C")

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(index="B")

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop(index=["B"])

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.drop("C" ,axis=0)#burda 0 yada 1 vermn lazim satirmi sutun

In [ ]:
df4=df3.drop("C",axis=0)

In [ ]:
df4

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
#loccation kisanltmasi yazan ibareye islem yapiyor,iloc index loca kisalltmasi

In [ ]:
#ilog ise arka planda tuttugu index numarasina gore yapa r son haneyi haric birakir

In [ ]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

 ### Removing rows

## Selecting Rows

### First, let's take a quick look at [`.loc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-loc.ipynb) | [`.iloc[]`](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-iloc.ipynb)

#### `.loc[]` → allows us to select data using **labels** (names) of rows (index) & columns

#### `.iloc[]` → allows us to select data using **index numbers** of rows (index) & columns. it's like classical indexing logic

#### Let's continue to examine `.loc[]` and `.iloc[]` using ``df3`` again

### Selecting subset of rows and columns

 - ### `.loc[[row labels|names], [column labels|names]]`

 - ### `.iloc[[row index numbers], [column index numbers]]`

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

#### For two conditions you can use **|** → `or`,  **&** →  `and` with parenthesis:

### Conditional selection using ``.loc[]`` and ``.iloc[]``

In [ ]:
df3

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
df3>2

W      X      Y      Z
A  False  False  False  False
B  False  False  False  False
C  False  False  False   True
D  False  False  False   True
E   True  False   True   True

In [ ]:
df3[df3>2]#elimizde tablo var olmayanlari non dondurdu
#koesli parantez iicndeki yaana uyani verir gerisine de non der

W   X         Y    Z
A       NaN NaN       NaN  NaN
B       NaN NaN       NaN  NaN
C       NaN NaN       NaN  3.0
D       NaN NaN       NaN  4.0
E  2.605967 NaN  5.156577  5.0

In [ ]:
df3

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
#z sutununda bana 0.5 altindaki getir
df3[df3["Z"]>0.5]

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
df3[df3["Z"]>0.5]["X"]#data fram olarak gormek icin cift parantez yap

A    0.503826
B    0.605965
C   -0.589001
D    0.955057
E    0.683509
Name: X, dtype: float64

In [ ]:
df3[df3["Z"]>0.5][["X"]]

X
A  0.503826
B  0.605965
C -0.589001
D  0.955057
E  0.683509

In [ ]:
#satirla ilgili condition yazmak dogru degil bir kismi string boolen int olu
#conditionlar sutun bazinda yazilri ona gorede secme yapilir

In [ ]:
df3[(df3['W']>0) & (df3['Y']<1)] 

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [ ]:
df3

W         X         Y  Z
A  0.000000  0.000000  0.000000  0
B -0.848077  0.605965  0.270806  2
C  0.000000  0.000000  0.000000  0
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
#ilk df3 u calistirdik
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3[(df3['W']>0) & (df3['Y']<1)] =0

In [ ]:
df3

W         X         Y         Z
A  0.000000  0.000000  0.000000  0.000000
B  0.000000  0.000000  0.000000  0.000000
C -2.018168  0.740122  0.528813 -0.589001
D  0.000000  0.000000  0.000000  0.000000
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
np.random.seed(101)
df3 = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'W X Y Z'.split())
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.loc[(df3.X>0),["X","Y"]]

X         Y
A  0.628133  0.907969
C  0.740122  0.528813
E  1.978757  2.605967

In [ ]:
df3.loc[((df3.W>1) | (df3.Y<1)), ['Y','Z']]#=1 dersen bu coditionlari 1 yapar
#satirlari belli seylere gore filitre yapiyor ona gore sutunlari cagiriyor


Y         Z
A  0.907969  0.503826
B -0.848077  0.605965
C  0.528813 -0.589001
D -0.933237  0.955057

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
m = np.random.randint(1,40, size=(8,4))
df4 = pd.DataFrame(m, columns = ["var1","var2","var3",'var4'])
df4

var1  var2  var3  var4
0     8    11    39    10
1    19     8    16     1
2    13    18    12    16
3    34    30    25    37
4    20    36    31    11
5    21    28     9    23
6    27    24    38    23
7    10     3    19    29

In [ ]:
df4.index='a b c d e f g h'.split()
df4

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37
e    20    36    31    11
f    21    28     9    23
g    27    24    38    23
h    10     3    19    29

In [ ]:
df4.iloc[1:4]# 4 u dahil etmedi arka planda  tuttugu index numaralarina gorre islem yaapr
#loc ne yaziyirsa ona bakar indexin etiketi ne ise ona bakr

var1  var2  var3  var4
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [ ]:
#loc da hata verir cunku benim indexlerim rakam degil harf hata verir
df4.loc[1:4]

TypeError: ignored

In [ ]:
df4.loc["a":"d"]

var1  var2  var3  var4
a     8    11    39    10
b    19     8    16     1
c    13    18    12    16
d    34    30    25    37

In [ ]:
#ortadaki 30 a ulasmak istyorum df4 de ilocda kendin sayman lazim getirmek icin
df4.iloc[3,1]

30

In [ ]:
#ama locda gordugunu getir
df4.loc["d","var2"]

30

In [ ]:
#araylrde yaptigimizin aynis sade basina loc iloc geldi

In [ ]:
df4.loc["d":"g","var3"]#series olarak istiyoz

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [ ]:
df4.loc[d]

In [ ]:
#ben bunu seri degil  data frame istersem bir koseli pranteze daha alrim.
df4.loc["d":"g"]["var3"]

d    25
e    31
f     9
g    38
Name: var3, dtype: int64

In [ ]:
df4.loc["d":"g"][["var3"]]

var3
d    25
e    31
f     9
g    38

In [ ]:
df4.loc["d":"g",["var3"]]

var3
d    25
e    31
f     9
g    38

In [ ]:
#bunlari iloc ile yapsaydim
df4.iloc[2:5,2]

c    12
d    25
e    31
Name: var3, dtype: int64

In [ ]:
df4.loc['d':'g'][['var3']]

var3
d    25
e    31
f     9
g    38

In [ ]:
df4.loc['d':'g'][['var2']]

var2
d    30
e    36
f    28
g    24

In [ ]:
#buraya dikkat ! iloc olursa int değer vermek zorundasınız. Yoksa hata olur. (i)loc kısmında ki i harfini int dan aklınızda tutabilirsiniz

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
df3.loc["C"]

W    0.528813
X   -0.589001
Y    0.391387
Z    3.000000
Name: C, dtype: float64

In [ ]:
df3.iloc[3]

W   -0.933237
X    0.955057
Y    0.708208
Z    4.000000
Name: D, dtype: float64

In [ ]:
df3.iloc[[2]]

W         X         Y  Z
C  0.528813 -0.589001  0.391387  3

In [ ]:
df3

W         X         Y  Z
A  0.907969  0.503826  0.570325  1
B -0.848077  0.605965  0.270806  2
C  0.528813 -0.589001  0.391387  3
D -0.933237  0.955057  0.708208  4
E  2.605967  0.683509  5.156577  5

In [ ]:
#c ile z nin kesimi 
#2 side koseli paranteze alirsam tek rakamim gelir
df3.loc["C","Z"]

3

In [ ]:
df3.loc[["C"],["Z"]]

Z
C  3

In [ ]:
df3.loc[["A","C"],["X","Z"]]#fany index capraz olarak aliyor kesisim aliyr

X  Z
A  0.503826  1
C -0.589001  3

In [ ]:
df3.iloc[[0,2],[0,3]]

W  Z
A  0.907969  1
C  0.528813  3

In [ ]:
df3

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
df3.reset_index()#

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [ ]:
#eskisi dusurur yenisinu yerine koyar
df3.reset_index(drop=True)

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

In [ ]:
#z yi aldi index e getirdi eskisini atti
df3.set_index("Z")

W         X         Y
Z                                      
 0.503826  2.706850  0.628133  0.907969
 0.605965  0.651118 -0.319318 -0.848077
-0.589001 -2.018168  0.740122  0.528813
 0.955057  0.188695 -0.758872 -0.933237
 0.683509  0.190794  1.978757  2.605967

In [ ]:
#lkalici olsun diye implace li yapiyoruz
df3.reset_index(drop=True,inplace=True)

In [ ]:
df3

W         X         Y         Z
0  2.706850  0.628133  0.907969  0.503826
1  0.651118 -0.319318 -0.848077  0.605965
2 -2.018168  0.740122  0.528813 -0.589001
3  0.188695 -0.758872 -0.933237  0.955057
4  0.190794  1.978757  2.605967  0.683509

### let's take a quick look at the [``.xs()``](http://localhost:8888/notebooks/pythonic/DAwPythonSessions/w3resource-pandas-dataframe-xs.ipynb)

### Let's learn new functions/attributes/methods on "iris dataset" 

# End of the Session