<a href="https://colab.research.google.com/github/eildes06/Inclassnotesandcodes/blob/main/Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [ ]:
arr_2d[0,2]

15

In [ ]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

array([-4., -3., -2., -1.,  0.])

In [ ]:
import numpy as np
arr_1 = np.array([5,6,7])
arr_2 = np.array([4,5,6])
arr_1-arr_2

array([1, 1, 1])

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 50]])

In [ ]:
arr_2d[:1,1:]

array([[10, 15]])

In [ ]:
arr_1 = np.arange(0,10)
arr_1


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr_2 = arr_1 * 3
arr_2

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [ ]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

array([0., 0., 0., 0., 0.])

In [ ]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)

array([2., 3., 4., 5., 6.])

In [ ]:
np.max(arr_2)

In [ ]:
arr=np.arange(1,37)
arr.shape

(36,)