<a href="https://colab.research.google.com/github/eildes06/Inclassnotesandcodes/blob/main/Statistics_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Descriptive Statistics

 Import **NumPy**, **SciPy**, and **Pandas**

In [37]:
import numpy as np
from scipy import stats
import pandas as pd
import matplotlib.pyplot as plt

 Randomly generate 1,000 samples from the normal distribution using `np.random.normal()`(mean = 100, standard deviation = 15)

In [36]:
samples =np.random.normal(100,15,1000)
samples

array([118.92195713, 110.98492947, 102.88118406, 115.34397786,
       104.65726532,  58.82027163,  95.65154545, 114.28892985,
       105.6542777 ,  97.39110822,  61.38843656,  88.96975844,
        74.05143544, 100.66220439, 109.76599247, 105.12350448,
        92.18449357, 111.99054413,  88.35614326, 111.69202817,
       112.79535994,  90.77603457,  87.20866657,  85.5104259 ,
       107.66093796,  91.62881946, 109.24613859,  80.42591113,
        76.96207741, 106.68547311,  99.49061246,  80.82267476,
        88.7178185 , 122.00219057, 101.51872865, 133.37023351,
       114.59109709, 103.44156035,  73.56019352,  87.15134478,
        86.16286025, 131.66318347,  95.21330012, 123.450068  ,
       127.75892765, 111.59680122, 118.83907232, 102.59432128,
        94.36619736, 108.86231385, 111.82905649, 107.66045968,
        95.40713205, 104.02045481,  85.52807615, 105.00438765,
        73.57719006,  99.34484866, 110.97162398, 115.007297  ,
       118.92819509,  83.19957462, 107.23923284,  94.53

Compute the **mean**, **median**, and **mode**

In [35]:
mean=np.mean(samples)
median =np.median(samples)
#mode =stats.mode(samples)
mean
median

100.20071553500466

Compute the **min**, **max**, **Q1**, **Q3**, and **interquartile range**

In [34]:
min = np.min(samples)
max =np.max(samples)
q1 =np.percentile(samples,25)
q3 =np.percentile(samples,75)
iqr =q3-q1
print(min)
print(max)
print(q1)
print(q3)
print(iqr)


53.23471129697427
148.5638447772275
89.7553188378769
109.99957282971488
20.24425399183798


Compute the **variance** and **standard deviation**

In [33]:
variance = np.var(samples)
std_dev =np.std(samples)
print(variance)
print(std_dev)

222.87266954060937
14.928920575199312


Compute the **skewness** and **kurtosis**

In [38]:
skewness =stats.skew(samples)
kurtosis =stats.kurtosis(samples)
print(skewness)
print(kurtosis)

-0.07335708221130754
-0.12773043573078846


## NumPy Correlation Calculation

Create an array x of integers between 10 (inclusive) and 20 (exclusive). Use `np.arange()`

In [30]:
x = np.arange(10,20)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

Then use `np.array()` to create a second array y containing 10 arbitrary integers.

In [41]:
y = np.random.randint(1,100,10)
print(y)

[ 1 48 39  8 69 76 20 96 51 59]


Once you have two arrays of the same length, you can compute the **correlation coefficient** between x and y

In [43]:
r = np.corrcoef(x,y)
r

array([[1.       , 0.5257767],
       [0.5257767, 1.       ]])

In [44]:
r = np.corrcoef(y,x)
r

array([[1.       , 0.5257767],
       [0.5257767, 1.       ]])

## Pandas Correlation Calculation

Run the code below

In [45]:
x = pd.Series(range(10, 20))
y = pd.Series([2, 1, 4, 5, 8, 12, 18, 25, 96, 48])

Call the relevant method  to calculate Pearson's r correlation.

In [47]:
r = x.corr(y)
r= y.corr(x)
r

0.7586402890911869

OPTIONAL. Call the relevant method to calculate Spearman's rho correlation.

In [48]:
rho = x.corr(y, method='spearman') 
rho

0.9757575757575757

## Seaborn Dataset Tips

Import Seaborn Library

In [53]:
import seaborn as sns

Load "tips" dataset from Seaborn

In [55]:
tips = sns.load_dataset("tips")
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

Generate descriptive statistics include those that summarize the central tendency, dispersion

In [56]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

Call the relevant method to calculate pairwise Pearson's r correlation of columns

In [57]:
tips.corr('pearson')

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000